# Example workflow using the venv composite action
name: Test venv
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Create Virtual Environment
      id: venv-and-run
      uses: marvinkronsbein/py-venv-composite-action@v1.2.2
      with:
        python-version: '3.8'
        requirements-file: 'requirements/files/requirements.txt'
        constraints-file: 'requirements/files/constraints.txt'
        run: |
          python -m pip list
